# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Euphoric Youths
# email: your-email@example.com
description:
  We make music, we make art, we make friends. We are Euphoric Youths.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://euphoricyouths.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme
remote_theme: jekyll/minima

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

header_pages:
  - about.md

author:
  name: © 2023 Euphoric Youths. All rights reserved.
  # email: 

minima:
  skin: auto
  social_links:
    - { platform: applemusic, user_url: "https://music.apple.com/artist/euphoric-youths/1708614378" }
    - { platform: instagram,  user_url: "https://www.instagram.com/euphoric_youths/" }
    - { platform: soundcloud, user_url: "https://soundcloud.com/euphoric-youths" }
    - { platform: spotify,    user_url: "https://open.spotify.com/artist/6cFIGJdR60nxi53Sx1hmzs?si=sxY3S4W5SUiamMCh7yAwoA"}
    - { platform: twitter,    user_url: "https://twitter.com/EuphoricYouths" }
    - { platform: youtube,    user_url: "https://www.youtube.com/@EuphoricYouths" }
